Import('env libraryPath platform')

src = Split("""
    VideoFFMPEG.cpp
    """)

pEnv = env.Clone()

if platform.system() == "Linux":
  pEnv.ParseConfig('pkg-config --cflags --libs libavutil')
  pEnv.ParseConfig('pkg-config --cflags --libs libavformat')
  pEnv.ParseConfig('pkg-config --cflags --libs libavcodec')

screenplay = pEnv.SharedLibrary('Screenplay', src)

env.Install(libraryPath, [screenplay])
