Import('env libraryPath')

src = Split("""
    KeyStone.cpp
    LensCorrection.cpp
    Random.cpp
    Rect.cpp
    Histogram.cpp
    """)

nimble = env.SharedLibrary('Nimble', src)

env.Install(libraryPath, [nimble])
