Import('env libraryPath')
import platform

src = Split("""
    ImageCodecJPEG.cpp
    ImageCodecPNG.cpp
    CodecRegistry.cpp
    ImageCodecTGA.cpp
    BGThread.cpp
    Collectable.cpp
    CPUMipmaps.cpp
    DynamicTexture.cpp
    Error.cpp
    FramebufferObject.cpp
    GarbageCollector.cpp
    GLKeyStone.cpp
    GLResource.cpp
    GLResources.cpp
    GLSLProgramObject.cpp
    GLSLShaderObject.cpp
    GPUMipmaps.cpp
    Image.cpp
    Luminous.cpp
    MultiHead.cpp
    Path.cpp
    PixelFormat.cpp
    Task.cpp
    TCBSpline.cpp
    Texture.cpp
    Utils.cpp
    VertexBuffer.cpp
    """)

pEnv = env.Clone()

if platform.system() == "Windows":
	pEnv.Append(CPPPATH = Split('../Win32x/include/libjpeg'))
	pEnv.Append(CCFLAGS = Split('-DLUMINOUS_EXPORT'))
	pEnv.Append(LIBPATH = Split('../Win32x/lib'))
	pEnv.Append(LIBS = Split('libjpeg-static-mt.lib'))
else:
	pEnv.Append(LIBS = Split("jpeg png GLEW"))

lib = pEnv.SharedLibrary('Luminous', src)

env.Install(libraryPath, [lib])
